[App]
Name = "ai.h2o.wave.shopping-cart-recommendations"
Version = "1.2.0"
Title = "Shopping Cart Recommendations"
Description = "Demo of a recommendation engine on groceries items."
LongDescription="about.md"
Category = "Data Science"
Keywords = ["Data Science", "Wave", "Open Source", "Market Basket Analysis"]

[Runtime]
Module = "src.app"
RoutingMode = "BASE_URL"
